/* The scroll-reveal list lives twice: main.css §13 sets the hidden initial
   state, anim.js observes the same elements and reveals them. If one list
   gains a selector the other lacks, the mismatch is silent and ugly — an
   element either stays invisible forever, or never animates. This pins them
   together. */
"use strict";
const test = require("node:test");
const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");

const ROOT = path.join(__dirname, "..");
const css = fs.readFileSync(path.join(ROOT, "assets/css/main.css"), "utf8");
const js = fs.readFileSync(path.join(ROOT, "assets/js/anim.js"), "utf8");

test("reveal selectors match between main.css and anim.js", () => {
  // Stop at the `{` that opens the declaration block: the declarations
  // themselves contain commas (`transition: opacity …, transform …`) and would
  // otherwise be read as extra selectors.
  const block = css.match(
    /13\. Motion[\s\S]*?@media \(prefers-reduced-motion: no-preference\) \{\s*([\s\S]*?)\s*\{/
  );
  assert.ok(block, "could not find the reveal initial-state block in main.css");

  const fromCss = block[1]
    .split(",")
    .map((s) => s.trim())
    .filter(Boolean)
    .map((s) => s.replace(/^\.js\s+/, ""));

  const list = js.match(/var REVEAL = \[([\s\S]*?)\]\.join/);
  assert.ok(list, "could not find the REVEAL list in anim.js");
  const fromJs = list[1]
    .split(",")
    .map((s) => s.trim().replace(/^["']|["']$/g, ""))
    .filter(Boolean);

  assert.deepEqual(
    fromJs,
    fromCss,
    "anim.js REVEAL and main.css §13 must list the same selectors in the same order"
  );
});

test("no page still loads a motion library", () => {
  const pages = [];
  const walk = (dir) => {
    for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
      // `dist/` is regenerated by package-deploy; auditing it here would fail
      // on whatever the previous build happened to leave behind.
      if (entry.name.startsWith(".") || entry.name === "node_modules" || entry.name === "dist") continue;
      const full = path.join(dir, entry.name);
      if (entry.isDirectory()) walk(full);
      else if (entry.name.endsWith(".html")) pages.push(full);
    }
  };
  walk(ROOT);
  for (const page of pages) {
    const html = fs.readFileSync(page, "utf8");
    assert.equal(
      /gsap|ScrollTrigger/i.test(html),
      false,
      `${path.relative(ROOT, page)} still references a motion library`
    );
  }
});

test("only one script binds the FAQ accordion", () => {
  // main.js binds a disclosure handler to every .faq-row__q site-wide. A second
  // handler on the same button toggles each click twice, so the answer opens and
  // shuts in the same frame — which is exactly what faq.js shipped with once.
  const dir = path.join(ROOT, "assets", "js");
  const owners = fs
    .readdirSync(dir)
    .filter((f) => f.endsWith(".js"))
    .filter((f) => /\.faq-row__q[^]{0,400}addEventListener\(\s*["']click/.test(
      fs.readFileSync(path.join(dir, f), "utf8")
    ));
  assert.deepEqual(owners, ["main.js"], `FAQ accordion is bound by: ${owners.join(", ")}`);
});
